//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamkare.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntitiesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntitiesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hamkare.Resource.EntitiesResources", typeof(EntitiesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرش بازگشت.
        /// </summary>
        public static string AcceptReturn {
            get {
                return ResourceManager.GetString("AcceptReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس‌ها.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستور تایید.
        /// </summary>
        public static string ApprovalOrder {
            get {
                return ResourceManager.GetString("ApprovalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید بازگشت.
        /// </summary>
        public static string ApprovalReturn {
            get {
                return ResourceManager.GetString("ApprovalReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت شعبه.
        /// </summary>
        public static string BranchCalendar {
            get {
                return ResourceManager.GetString("BranchCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت‌های شعبه.
        /// </summary>
        public static string BranchCalendars {
            get {
                return ResourceManager.GetString("BranchCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات شعبه.
        /// </summary>
        public static string BranchComment {
            get {
                return ResourceManager.GetString("BranchComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات شعبه‌ها.
        /// </summary>
        public static string BranchComments {
            get {
                return ResourceManager.GetString("BranchComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه‌ها.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات محصول شعبه.
        /// </summary>
        public static string BranchProductService {
            get {
                return ResourceManager.GetString("BranchProductService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر‌ها.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور‌ها.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف.
        /// </summary>
        public static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل شعبه.
        /// </summary>
        public static string CouponBranchIncluded {
            get {
                return ResourceManager.GetString("CouponBranchIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر شامل شعبه.
        /// </summary>
        public static string CouponBranchNotIncluded {
            get {
                return ResourceManager.GetString("CouponBranchNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل گروه محصول.
        /// </summary>
        public static string CouponProductGroupIncluded {
            get {
                return ResourceManager.GetString("CouponProductGroupIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر شامل گروه محصول.
        /// </summary>
        public static string CouponProductGroupNotIncluded {
            get {
                return ResourceManager.GetString("CouponProductGroupNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل محصول.
        /// </summary>
        public static string CouponProductIncluded {
            get {
                return ResourceManager.GetString("CouponProductIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر شامل محصول.
        /// </summary>
        public static string CouponProductNotIncluded {
            get {
                return ResourceManager.GetString("CouponProductNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف‌ها.
        /// </summary>
        public static string Coupons {
            get {
                return ResourceManager.GetString("Coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل گروه سرویس.
        /// </summary>
        public static string CouponServiceGroupIncluded {
            get {
                return ResourceManager.GetString("CouponServiceGroupIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر شامل گروه سرویس.
        /// </summary>
        public static string CouponServiceGroupNotIncluded {
            get {
                return ResourceManager.GetString("CouponServiceGroupNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل سرویس.
        /// </summary>
        public static string CouponServiceIncluded {
            get {
                return ResourceManager.GetString("CouponServiceIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر شامل سرویس.
        /// </summary>
        public static string CouponServiceNotIncluded {
            get {
                return ResourceManager.GetString("CouponServiceNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل کاربر.
        /// </summary>
        public static string CouponUserIncluded {
            get {
                return ResourceManager.GetString("CouponUserIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر شامل کاربر.
        /// </summary>
        public static string CouponUserNotIncluded {
            get {
                return ResourceManager.GetString("CouponUserNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتباری.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه دوره‌ها.
        /// </summary>
        public static string DownloadGroup {
            get {
                return ResourceManager.GetString("DownloadGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره‌ها.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویژگی.
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویژگی‌ها.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا‌ها.
        /// </summary>
        public static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال پیش رفت.
        /// </summary>
        public static string Inprogress {
            get {
                return ResourceManager.GetString("Inprogress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حمل و نقل.
        /// </summary>
        public static string InShipping {
            get {
                return ResourceManager.GetString("InShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه فرآیند.
        /// </summary>
        public static string JobHistory {
            get {
                return ResourceManager.GetString("JobHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فرآیند.
        /// </summary>
        public static string JobInfo {
            get {
                return ResourceManager.GetString("JobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ها.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت فرآیند.
        /// </summary>
        public static string JobState {
            get {
                return ResourceManager.GetString("JobState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع درخواست.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبرنامه.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات خبرنامه.
        /// </summary>
        public static string NewsComment {
            get {
                return ResourceManager.GetString("NewsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی خبر.
        /// </summary>
        public static string NewsGroup {
            get {
                return ResourceManager.GetString("NewsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت اعلانات.
        /// </summary>
        public static string NotificationSubscription {
            get {
                return ResourceManager.GetString("NotificationSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات سفارش.
        /// </summary>
        public static string OrderComment {
            get {
                return ResourceManager.GetString("OrderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات سفارش.
        /// </summary>
        public static string OrderItem {
            get {
                return ResourceManager.GetString("OrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارشات.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت‌ها.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص حقوقی.
        /// </summary>
        public static string PersonLegal {
            get {
                return ResourceManager.GetString("PersonLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشخاص.
        /// </summary>
        public static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات محصول.
        /// </summary>
        public static string ProductComment {
            get {
                return ResourceManager.GetString("ProductComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته‌بندی محصولات.
        /// </summary>
        public static string ProductGroup {
            get {
                return ResourceManager.GetString("ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر URL.
        /// </summary>
        public static string Redirect {
            get {
                return ResourceManager.GetString("Redirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییرات URL.
        /// </summary>
        public static string Redirects {
            get {
                return ResourceManager.GetString("Redirects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مناطق.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد بازگشت.
        /// </summary>
        public static string RejectReturn {
            get {
                return ResourceManager.GetString("RejectReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگشت.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمت.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقویم خدمات.
        /// </summary>
        public static string ServiceCalendar {
            get {
                return ResourceManager.GetString("ServiceCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات خدمات.
        /// </summary>
        public static string ServiceComment {
            get {
                return ResourceManager.GetString("ServiceComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی خدمات.
        /// </summary>
        public static string ServiceGroup {
            get {
                return ResourceManager.GetString("ServiceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهارت.
        /// </summary>
        public static string ServiceSkill {
            get {
                return ResourceManager.GetString("ServiceSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان‌ها.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آمار.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برچسب.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برچسب‌ها.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش‌ها.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال مرسوله.
        /// </summary>
        public static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات ارسال.
        /// </summary>
        public static string TransportationComments {
            get {
                return ResourceManager.GetString("TransportationComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه ارسال.
        /// </summary>
        public static string TransportationCost {
            get {
                return ResourceManager.GetString("TransportationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع ارسال.
        /// </summary>
        public static string Transportations {
            get {
                return ResourceManager.GetString("Transportations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقویم ارسال.
        /// </summary>
        public static string TransportationsCalendar {
            get {
                return ResourceManager.GetString("TransportationsCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه کاربران.
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
