//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamkare.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hamkare.Resource.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه دسترسی به این آدرس را ندارید.
        /// </summary>
        public static string AccessAddressError {
            get {
                return ResourceManager.GetString("AccessAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه دسترسی به این سفارش را ندارید.
        /// </summary>
        public static string AccessOrderError {
            get {
                return ResourceManager.GetString("AccessOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار شهر به درستی انتخاب نشده است.
        /// </summary>
        public static string CityError {
            get {
                return ResourceManager.GetString("CityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدهای {0} تکراری می‌باشد.
        /// </summary>
        public static string CouponRepeatError {
            get {
                return ResourceManager.GetString("CouponRepeatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ {0} نباید بزرگتر از تاریخ {1} باشد!.
        /// </summary>
        public static string DateNotGreaterThen {
            get {
                return ResourceManager.GetString("DateNotGreaterThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ {0} نباید بزرگتر از تاریخ روز باشد!.
        /// </summary>
        public static string DateNotGreaterThenCurrent {
            get {
                return ResourceManager.GetString("DateNotGreaterThenCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ {0} نباید کوچکتر از تاریخ {1} باشد!.
        /// </summary>
        public static string DateNotLessThen {
            get {
                return ResourceManager.GetString("DateNotLessThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ {0} نباید کوچکتر از تاریخ روز باشد!.
        /// </summary>
        public static string DateNotLessThenCurrent {
            get {
                return ResourceManager.GetString("DateNotLessThenCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به طور همزمان نمی تواند زمان و روز را انتخاب کرد!
        ///لطفا بخش زمان را حذف نمایید!.
        /// </summary>
        public static string DayMode {
            get {
                return ResourceManager.GetString("DayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به طور همزمان نمی تواند زمان و روز را انتخاب کرد!
        ///لطفا بخش تاریخ یا بخش زمان را به صورت یکتا وارد کنید!.
        /// </summary>
        public static string DayModeAndTimeMode {
            get {
                return ResourceManager.GetString("DayModeAndTimeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز یا زمان در هفته مشخص نشده است!.
        /// </summary>
        public static string DaymodeOrTimeModeNotSelected {
            get {
                return ResourceManager.GetString("DaymodeOrTimeModeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف نمی تواند از مبلغ کل بیشتر باشد..
        /// </summary>
        public static string DiscountCannotTotalAmount {
            get {
                return ResourceManager.GetString("DiscountCannotTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در هر بخش باید یک زبان فعال موجود باشد!.
        /// </summary>
        public static string DisplayItemsNotActive {
            get {
                return ResourceManager.GetString("DisplayItemsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url وارد شده تکراری است !.
        /// </summary>
        public static string DuplicateUrl {
            get {
                return ResourceManager.GetString("DuplicateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت انتخاب موجودیت باید شناسه را نیز وارد کنید!.
        /// </summary>
        public static string EntityTypeMustBeDefind {
            get {
                return ResourceManager.GetString("EntityTypeMustBeDefind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع و پایان نمی‌تواند برابر باشد.
        /// </summary>
        public static string ErorrStartAndEndcannotEqual {
            get {
                return ResourceManager.GetString("ErorrStartAndEndcannotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک شعبه نمی‌تواند هم در بخش شامل و غیر باشد.
        /// </summary>
        public static string ErrorCouponBranch {
            get {
                return ResourceManager.GetString("ErrorCouponBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی که به کد تخفیف نیاز ندارید باید یک اعتبار ثبت نمایید.
        /// </summary>
        public static string ErrorCouponCredit {
            get {
                return ResourceManager.GetString("ErrorCouponCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف نمی تواند شامل تخفیف درصدی و تخفیف ثابت باشد.
        /// </summary>
        public static string ErrorCouponPercent {
            get {
                return ResourceManager.GetString("ErrorCouponPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت {0} با مشکل روبرو شده است!.
        /// </summary>
        public static string ErrorSubmit {
            get {
                return ResourceManager.GetString("ErrorSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد کاراکتر {0} باید {1} باشد!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار شهر به درستی انتخاب نشده است.
        /// </summary>
        public static string NotCorrectCity {
            get {
                return ResourceManager.GetString("NotCorrectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار استان به درستی انتخاب نشده است.
        /// </summary>
        public static string NotCorrectState {
            get {
                return ResourceManager.GetString("NotCorrectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید به صورت اعداد باشد!.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} نباید بزرگتر از مقدار {1} باشد!.
        /// </summary>
        public static string NumberNotGreaterThen {
            get {
                return ResourceManager.GetString("NumberNotGreaterThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} نباید کوچکتر از مقدار {1} باشد!.
        /// </summary>
        public static string NumberNotLessThen {
            get {
                return ResourceManager.GetString("NumberNotLessThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مورد در سبد خرید باید بزرگتر از صفر باشد.
        /// </summary>
        public static string NumberShoppingGreaterZero {
            get {
                return ResourceManager.GetString("NumberShoppingGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه دسترسی به این سفارش را ندارید.
        /// </summary>
        public static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بین {1} و {2} باشد!.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا {0} را وارد کنید!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت و تغییر به {0} فعال نیاز است!.
        /// </summary>
        public static string RequiredNotFound {
            get {
                return ResourceManager.GetString("RequiredNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس پیامک به درستی انتخاب نشده است!.
        /// </summary>
        public static string SmsServiceNotFind {
            get {
                return ResourceManager.GetString("SmsServiceNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این داده به صورت سیستمی بوده و امکان حذف ندارد.
        /// </summary>
        public static string SystematicData {
            get {
                return ResourceManager.GetString("SystematicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به طور همزمان نمی تواند زمان و روز را انتخاب کرد!
        ///لطفا بخش تاریخ را حذف نمایید!.
        /// </summary>
        public static string TimeMode {
            get {
                return ResourceManager.GetString("TimeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان {0} نباید بزرگتر از زمان {1} باشد!.
        /// </summary>
        public static string TimeNotGreaterThen {
            get {
                return ResourceManager.GetString("TimeNotGreaterThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان {0} نباید بزرگتر از زمان امروز باشد!.
        /// </summary>
        public static string TimeNotGreaterThenCurrent {
            get {
                return ResourceManager.GetString("TimeNotGreaterThenCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان {0} نباید کوچکتر از زمان {1} باشد!.
        /// </summary>
        public static string TimeNotLessThen {
            get {
                return ResourceManager.GetString("TimeNotLessThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان {0} نباید کوچکتر از زمان امروز باشد!.
        /// </summary>
        public static string TimeNotLessThenCurrent {
            get {
                return ResourceManager.GetString("TimeNotLessThenCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویژگی {0} در {1} یافت نشده!.
        /// </summary>
        public static string UnknownProperty {
            get {
                return ResourceManager.GetString("UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} معتبر نمی باشد!.
        /// </summary>
        public static string ValueIsNotValid {
            get {
                return ResourceManager.GetString("ValueIsNotValid", resourceCulture);
            }
        }
    }
}
