//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamkare.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hamkare.Resource.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مورد نظر فعال شد!.
        /// </summary>
        public static string ActiveMessage {
            get {
                return ResourceManager.GetString("ActiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سئو و نمایش تمامی صفحات استفاده خواهد شد.
        /// </summary>
        public static string AllPageSEOandDisplayHelper {
            get {
                return ResourceManager.GetString("AllPageSEOandDisplayHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سئو تمامی صفحات استفاده خواهد شد..
        /// </summary>
        public static string AllPageSEOHelper {
            get {
                return ResourceManager.GetString("AllPageSEOHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربی.
        /// </summary>
        public static string Ar {
            get {
                return ResourceManager.GetString("Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودکار.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Bale {
            get {
                return ResourceManager.GetString("Bale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایه واحد پولی.
        /// </summary>
        public static string BaseCurrencyHelper {
            get {
                return ResourceManager.GetString("BaseCurrencyHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن تکرار شونده در ابتدای تمامی صفحات.
        /// </summary>
        public static string BodyHelper {
            get {
                return ResourceManager.GetString("BodyHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه بسته بندی.
        /// </summary>
        public static string BoxingCost {
            get {
                return ResourceManager.GetString("BoxingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً وضعیت را انتخاب کنید.
        /// </summary>
        public static string ChooseStatus {
            get {
                return ResourceManager.GetString("ChooseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کلاس.
        /// </summary>
        public static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس برای نمایش در سئو.
        /// </summary>
        public static string ContactPointHelper {
            get {
                return ResourceManager.GetString("ContactPointHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوا.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل مدیریت.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد‌کننده.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ایجادکننده.
        /// </summary>
        public static string CreatorId {
            get {
                return ResourceManager.GetString("CreatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت وارد کردن صفر واحد پولی غیر فعال خواهد شد..
        /// </summary>
        public static string CurrencyHelper {
            get {
                return ResourceManager.GetString("CurrencyHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز هفته.
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مورد نظر غیرفعال شد!.
        /// </summary>
        public static string DeactivateMessage {
            get {
                return ResourceManager.GetString("DeactivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار پیش‌فرض.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف {0} با موفقیت انجام شد!.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این توضیحات به صورت سئو و پاپ آپ نمایش داده خواهد شد.
        /// </summary>
        public static string DisplayedSEOPopUps {
            get {
                return ResourceManager.GetString("DisplayedSEOPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش‌ها.
        /// </summary>
        public static string DisplayItems {
            get {
                return ResourceManager.GetString("DisplayItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ویرایش.
        /// </summary>
        public static string EditDate {
            get {
                return ResourceManager.GetString("EditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش‌کننده.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ویرایش‌کننده.
        /// </summary>
        public static string EditorId {
            get {
                return ResourceManager.GetString("EditorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایتا.
        /// </summary>
        public static string Eitaa {
            get {
                return ResourceManager.GetString("Eitaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پورت سرور ایمیل.
        /// </summary>
        public static string EmailPort {
            get {
                return ResourceManager.GetString("EmailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرسی که ایمیل با آن ارسال می‌شود.
        /// </summary>
        public static string EmailSenderAddress {
            get {
                return ResourceManager.GetString("EmailSenderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس سرور ایمیل.
        /// </summary>
        public static string EmailServerAddress {
            get {
                return ResourceManager.GetString("EmailServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور سرور ایمیل.
        /// </summary>
        public static string EmailServerPassword {
            get {
                return ResourceManager.GetString("EmailServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری سرور ایمیل.
        /// </summary>
        public static string EmailServerUsername {
            get {
                return ResourceManager.GetString("EmailServerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انگلیسی.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پایان.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌ها.
        /// </summary>
        public static string EntityId {
            get {
                return ResourceManager.GetString("EntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرخ ارز.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string Fa {
            get {
                return ResourceManager.GetString("Fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیس بوک.
        /// </summary>
        public static string FaceBook {
            get {
                return ResourceManager.GetString("FaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات متداول.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمومی.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات عمومی.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقویم میلادی.
        /// </summary>
        public static string GregorianCalendar {
            get {
                return ResourceManager.GetString("GregorianCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سربرگ.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش هدر تکرار شونده در تمام صفحات.
        /// </summary>
        public static string HeaderHelper {
            get {
                return ResourceManager.GetString("HeaderHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتفاع.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس‌ها.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمو.
        /// </summary>
        public static string Imo {
            get {
                return ResourceManager.GetString("Imo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینستاگرام.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرایه ارسال پیامک فرآیند ها به صورت [{&apos;TemplateId&apos;:249611,&apos;EntityId&apos;:1,&apos;EntityType&apos;:&apos;Job&apos;}].
        /// </summary>
        public static string JobSmsHelper {
            get {
                return ResourceManager.GetString("JobSmsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمات مرتبط.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این زبان نمایش داده شود.
        /// </summary>
        public static string LanguageDisplay {
            get {
                return ResourceManager.GetString("LanguageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان های استفاد شده در سایت به صورت fa,en,ar,tr.
        /// </summary>
        public static string LanguageHelper {
            get {
                return ResourceManager.GetString("LanguageHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جغرافیایی.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینکدین.
        /// </summary>
        public static string Linkedin {
            get {
                return ResourceManager.GetString("Linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب استفاده شده برای ورود به سایت.
        /// </summary>
        public static string LoginTemplateHelper {
            get {
                return ResourceManager.GetString("LoginTemplateHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول جغرافیایی.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقیقه.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره‌های من.
        /// </summary>
        public static string MyCourses {
            get {
                return ResourceManager.GetString("MyCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات پاسخ‌گویی در سئو.
        /// </summary>
        public static string OpeningHoursHelper {
            get {
                return ResourceManager.GetString("OpeningHoursHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب نمایش در منو و صفحه اصلی.
        /// </summary>
        public static string OrderHelper {
            get {
                return ResourceManager.GetString("OrderHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالک.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مالک که در تمام موارد از جمله صفحه اصلی، پیامک، سئو استفاده خواهد شد..
        /// </summary>
        public static string OwnerNameHelper {
            get {
                return ResourceManager.GetString("OwnerNameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد سطر در هر صفحه:.
        /// </summary>
        public static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام صفحه مورد نظر.
        /// </summary>
        public static string PageNameHelper {
            get {
                return ResourceManager.GetString("PageNameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {first_item}-{last_item} از {all_items}.
        /// </summary>
        public static string PagesCountOf {
            get {
                return ResourceManager.GetString("PagesCountOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پدر.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه پدر.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگوی عنوان در مرورگر.
        /// </summary>
        public static string PathFavHelper {
            get {
                return ResourceManager.GetString("PathFavHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگو استفاده شده در تمامی صفحات.
        /// </summary>
        public static string PathLogoHelper {
            get {
                return ResourceManager.GetString("PathLogoHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن ثابت.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع محصول.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سامانه پیامکی.
        /// </summary>
        public static string ProviderHelper {
            get {
                return ResourceManager.GetString("ProviderHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت‌کننده.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه دریافت‌کننده.
        /// </summary>
        public static string ReceiverId {
            get {
                return ResourceManager.GetString("ReceiverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیرندگان.
        /// </summary>
        public static string Recipients {
            get {
                return ResourceManager.GetString("Recipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این مورد اطمینان دارید؟.
        /// </summary>
        public static string RemoveMessage {
            get {
                return ResourceManager.GetString("RemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لایسنس شما به درستی اعتبار سنجی شد.
        /// </summary>
        public static string RequestLicenseSuccess {
            get {
                return ResourceManager.GetString("RequestLicenseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روبیکا.
        /// </summary>
        public static string Robika {
            get {
                return ResourceManager.GetString("Robika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش‌ها.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روسی.
        /// </summary>
        public static string Ru {
            get {
                return ResourceManager.GetString("Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمامی لینک‌های اجتماعی به صورت آرایه.
        /// </summary>
        public static string SameAsHelper {
            get {
                return ResourceManager.GetString("SameAsHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به مشتری.
        /// </summary>
        public static string SendCustomer {
            get {
                return ResourceManager.GetString("SendCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرستنده.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌فرستنده.
        /// </summary>
        public static string SenderId {
            get {
                return ResourceManager.GetString("SenderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به گیرنده.
        /// </summary>
        public static string SendRecipient {
            get {
                return ResourceManager.GetString("SendRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سئو.
        /// </summary>
        public static string Seo {
            get {
                return ResourceManager.GetString("Seo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در منو.
        /// </summary>
        public static string ShowInMenu {
            get {
                return ResourceManager.GetString("ShowInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکایپ.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط ارسال کننده پیامک.
        /// </summary>
        public static string SMSNumberHelper {
            get {
                return ResourceManager.GetString("SMSNumberHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسانه های اجتماعی.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقویم شمسی.
        /// </summary>
        public static string SolarCalendar {
            get {
                return ResourceManager.GetString("SolarCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سروش.
        /// </summary>
        public static string Soroush {
            get {
                return ResourceManager.GetString("Soroush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت {0} با موفقیت انجام شد!.
        /// </summary>
        public static string SubmitSuccessMessage {
            get {
                return ResourceManager.GetString("SubmitSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالیات.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلگرام.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه قالب.
        /// </summary>
        public static string TemplateID {
            get {
                return ResourceManager.GetString("TemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن برنامه Tinymce.
        /// </summary>
        public static string TinymceTokenHelper {
            get {
                return ResourceManager.GetString("TinymceTokenHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان به صورت اجباریست.
        /// </summary>
        public static string TitleMandatory {
            get {
                return ResourceManager.GetString("TitleMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن سامانه پیامکی.
        /// </summary>
        public static string TokenHelper {
            get {
                return ResourceManager.GetString("TokenHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترکی.
        /// </summary>
        public static string Tr {
            get {
                return ResourceManager.GetString("Tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودیت آپلود فایل.
        /// </summary>
        public static string UploadLimitHelper {
            get {
                return ResourceManager.GetString("UploadLimitHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس صفحه.
        /// </summary>
        public static string URLHelper {
            get {
                return ResourceManager.GetString("URLHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام‌کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلم.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واتساپ.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چینی.
        /// </summary>
        public static string Zh {
            get {
                return ResourceManager.GetString("Zh", resourceCulture);
            }
        }
    }
}
