//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamkare.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hamkare.Resource.ViewResources", typeof(ViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی به این صفحه محدود شده است.
        /// </summary>
        public static string AccessRestricted {
            get {
                return ResourceManager.GetString("AccessRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرز.
        /// </summary>
        public static string Alborz {
            get {
                return ResourceManager.GetString("Alborz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همراه.
        /// </summary>
        public static string Along {
            get {
                return ResourceManager.GetString("Along", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقاله.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Friday.
        /// </summary>
        public static string BlackFriday {
            get {
                return ResourceManager.GetString("BlackFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با.
        /// </summary>
        public static string CallBy {
            get {
                return ResourceManager.GetString("CallBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر فکر می کنید اشتباه است، لطفا با مدیر سایت چک کنید.
        /// </summary>
        public static string CheckAdmin {
            get {
                return ResourceManager.GetString("CheckAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکتی.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیگیری.
        /// </summary>
        public static string Consistency {
            get {
                return ResourceManager.GetString("Consistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما به موفقیت ثبت شد.
        /// </summary>
        public static string ConsultationRequestSuccess {
            get {
                return ResourceManager.GetString("ConsultationRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همکاری با ما.
        /// </summary>
        public static string CooperationWithUs {
            get {
                return ResourceManager.GetString("CooperationWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلیه حقوق این سایت مربوط به تیم همکاره می باشد.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاق و هنرمند
        ///
        ///.
        /// </summary>
        public static string Creative {
            get {
                return ResourceManager.GetString("Creative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روزانه.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیره.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تحویل.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش نمایش.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی و تولید.
        /// </summary>
        public static string DesignedBy {
            get {
                return ResourceManager.GetString("DesignedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاهی.
        /// </summary>
        public static string Ecommrce {
            get {
                return ResourceManager.GetString("Ecommrce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقتصادی.
        /// </summary>
        public static string Economic {
            get {
                return ResourceManager.GetString("Economic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختصاصی.
        /// </summary>
        public static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منصف.
        /// </summary>
        public static string Fair {
            get {
                return ResourceManager.GetString("Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات متداول.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوگل ادز.
        /// </summary>
        public static string GoogleAds {
            get {
                return ResourceManager.GetString("GoogleAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعهد.
        /// </summary>
        public static string Guarantee {
            get {
                return ResourceManager.GetString("Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایران.
        /// </summary>
        public static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کرج.
        /// </summary>
        public static string Karaj {
            get {
                return ResourceManager.GetString("Karaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روشن.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً منتظر بمانید....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگو.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوکس.
        /// </summary>
        public static string Luxury {
            get {
                return ResourceManager.GetString("Luxury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میلیون تومان.
        /// </summary>
        public static string MillionTomans {
            get {
                return ResourceManager.GetString("MillionTomans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصوصیات ما.
        /// </summary>
        public static string OurCharacteristics {
            get {
                return ResourceManager.GetString("OurCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات ما.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحات.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت درخواست.
        /// </summary>
        public static string PhoneNumberError {
            get {
                return ResourceManager.GetString("PhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن وارد شده نامعتبر است.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تلفن خود را وارد کنید.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجربیات ما.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت ها.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشرو.
        /// </summary>
        public static string Progressive {
            get {
                return ResourceManager.GetString("Progressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی سریع.
        /// </summary>
        public static string QuickAccess {
            get {
                return ResourceManager.GetString("QuickAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشتر بخوانید.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب آماده.
        /// </summary>
        public static string ReadyTheme {
            get {
                return ResourceManager.GetString("ReadyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقاله های اخیر.
        /// </summary>
        public static string RecentArticles {
            get {
                return ResourceManager.GetString("RecentArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما با خطا مواجه شده است.
        /// </summary>
        public static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما با موفقیت ثبت شد.
        /// </summary>
        public static string RequestSuccess {
            get {
                return ResourceManager.GetString("RequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ استرداد.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئن.
        /// </summary>
        public static string Safe {
            get {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سئو و محتوا.
        /// </summary>
        public static string Seo {
            get {
                return ResourceManager.GetString("Seo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصص.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و جدید.
        /// </summary>
        public static string SubmitAndNew {
            get {
                return ResourceManager.GetString("SubmitAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزار تومان.
        /// </summary>
        public static string ThousandTomans {
            get {
                return ResourceManager.GetString("ThousandTomans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تقریبی خواندن.
        /// </summary>
        public static string TimeToRead {
            get {
                return ResourceManager.GetString("TimeToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تومان.
        /// </summary>
        public static string Toman {
            get {
                return ResourceManager.GetString("Toman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امانت داری.
        /// </summary>
        public static string Trusteeship {
            get {
                return ResourceManager.GetString("Trusteeship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درک متقابل.
        /// </summary>
        public static string Understanding {
            get {
                return ResourceManager.GetString("Understanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای غیرمنتظره.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مورد نمایش داده شود.
        /// </summary>
        public static string WillBeDisplayed {
            get {
                return ResourceManager.GetString("WillBeDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همکاری با ما.
        /// </summary>
        public static string WorkWithUs {
            get {
                return ResourceManager.GetString("WorkWithUs", resourceCulture);
            }
        }
    }
}
