//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamkare.Resource.Orders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrdersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrdersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hamkare.Resource.Orders.OrdersResources", typeof(OrdersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف روی کل فاکتور.
        /// </summary>
        public static string BoxingCostHelper {
            get {
                return ResourceManager.GetString("BoxingCostHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف روی کل فاکتور.
        /// </summary>
        public static string CountHelper {
            get {
                return ResourceManager.GetString("CountHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پرداخت سفارش و نهایی شدن آن.
        /// </summary>
        public static string DatePaymentOrder {
            get {
                return ResourceManager.GetString("DatePaymentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تحویل.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ارسال سفارش.
        /// </summary>
        public static string DeliveryDateHelper {
            get {
                return ResourceManager.GetString("DeliveryDateHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف روی کل فاکتور.
        /// </summary>
        public static string DiscountHelper {
            get {
                return ResourceManager.GetString("DiscountHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارشات من.
        /// </summary>
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کالا یا خدمات.
        /// </summary>
        public static string NameHelper {
            get {
                return ResourceManager.GetString("NameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سفارش.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پرداخت سفارش و نهایی شدن آن.
        /// </summary>
        public static string orderDateHelper {
            get {
                return ResourceManager.GetString("orderDateHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سفارش.
        /// </summary>
        public static string OrderState {
            get {
                return ResourceManager.GetString("OrderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این مرحله امکان ویرایش اقلام فاکتور وجود ندارد.
        /// </summary>
        public static string OrderStateError {
            get {
                return ResourceManager.GetString("OrderStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سفارش.
        /// </summary>
        public static string OrderStateHelper {
            get {
                return ResourceManager.GetString("OrderStateHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پیش سفارش.
        /// </summary>
        public static string PreOrderDate {
            get {
                return ResourceManager.GetString("PreOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کالا.
        /// </summary>
        public static string PriceHelper {
            get {
                return ResourceManager.GetString("PriceHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف روی کل فاکتور.
        /// </summary>
        public static string TaxHelper {
            get {
                return ResourceManager.GetString("TaxHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ کل تخفیف.
        /// </summary>
        public static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ قابل پرداخت.
        /// </summary>
        public static string TotalPayable {
            get {
                return ResourceManager.GetString("TotalPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه ارسال سفارش.
        /// </summary>
        public static string TransportationHelper {
            get {
                return ResourceManager.GetString("TransportationHelper", resourceCulture);
            }
        }
    }
}
