//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamkare.Resource.Identity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hamkare.Resource.Identity.IdentityResources", typeof(IdentityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ورود خطا.
        /// </summary>
        public static string AccessFailedCount {
            get {
                return ResourceManager.GetString("AccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال‌سازی.
        /// </summary>
        public static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا خود را برای برگشت وجه وارد کنید.
        /// </summary>
        public static string BankAccountHelper {
            get {
                return ResourceManager.GetString("BankAccountHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت بانکی.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت خود را برای برگشت وجه وارد کنید.
        /// </summary>
        public static string CardNumberHelper {
            get {
                return ResourceManager.GetString("CardNumberHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای {0} بر روی لینک کلیک کنید.
        /// </summary>
        public static string ClickOnLink {
            get {
                return ResourceManager.GetString("ClickOnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید رمز عبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید ایمیل.
        /// </summary>
        public static string EmailConfirm {
            get {
                return ResourceManager.GetString("EmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید ایمیل در {0}.
        /// </summary>
        public static string EmailConfirmSubject {
            get {
                return ResourceManager.GetString("EmailConfirmSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ایمیل نمی‌تواند خالی باشد.
        /// </summary>
        public static string EmailHelper {
            get {
                return ResourceManager.GetString("EmailHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل شما تایید شده است.
        /// </summary>
        public static string EmailIsConfirmed {
            get {
                return ResourceManager.GetString("EmailIsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل ارسال شد.
        /// </summary>
        public static string EmailIsSend {
            get {
                return ResourceManager.GetString("EmailIsSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل شما به آدرس {0} ارسال شد.
        /// </summary>
        public static string EmailIsSendDescription {
            get {
                return ResourceManager.GetString("EmailIsSendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل تکراری است لطفا ایمیل دیگری انتخاب کنید!.
        /// </summary>
        public static string ErrorDuplicateEmail {
            get {
                return ResourceManager.GetString("ErrorDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه تکراری است لطفا شماره همراه دیگری انتخاب کنید!.
        /// </summary>
        public static string ErrorDuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("ErrorDuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری است لطفا نام کاربری دیگری انتخاب کنید!.
        /// </summary>
        public static string ErrorDuplicateUsername {
            get {
                return ResourceManager.GetString("ErrorDuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه و یا ایمیل باید وارد گردد..
        /// </summary>
        public static string ErrorFillEmailAndPhoneNumberSametime {
            get {
                return ResourceManager.GetString("ErrorFillEmailAndPhoneNumberSametime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا شماره تماس خود را وارد کرده و یا از نام کاربری و رمز عبور استفاده کنید!.
        /// </summary>
        public static string ErrorLoginFill {
            get {
                return ResourceManager.GetString("ErrorLoginFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور وارد نشده است!.
        /// </summary>
        public static string ErrorNoPassword {
            get {
                return ResourceManager.GetString("ErrorNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار رمز عبور باید برابر باشد!.
        /// </summary>
        public static string ErrorPasswordCompare {
            get {
                return ResourceManager.GetString("ErrorPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید شامل حروف بزرگ و حروف کوچک و اعداد باشد!.
        /// </summary>
        public static string ErrorPasswordIsNotValid {
            get {
                return ResourceManager.GetString("ErrorPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیر فعال شده است.
        ///لطفا با مدیر سامانه تماس بگیرید..
        /// </summary>
        public static string ErrorUserIsNotActive {
            get {
                return ResourceManager.GetString("ErrorUserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری یافت نشد..
        /// </summary>
        public static string ErrorUserNotFind {
            get {
                return ResourceManager.GetString("ErrorUserNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و نام کاربری اشتباه است..
        /// </summary>
        public static string ErrorWrongPassword {
            get {
                return ResourceManager.GetString("ErrorWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضا کد.
        /// </summary>
        public static string ExpireActivationCode {
            get {
                return ResourceManager.GetString("ExpireActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن نامعتبر است..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما قفل شده است..
        /// </summary>
        public static string IsLockOut {
            get {
                return ResourceManager.GetString("IsLockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیرفعال شده است..
        /// </summary>
        public static string IsNotAllowed {
            get {
                return ResourceManager.GetString("IsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قفل کاربر.
        /// </summary>
        public static string LockoutEnabled {
            get {
                return ResourceManager.GetString("LockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان مسدودی.
        /// </summary>
        public static string LockoutEnd {
            get {
                return ResourceManager.GetString("LockoutEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با نام کاربری.
        /// </summary>
        public static string LoginWithEmail {
            get {
                return ResourceManager.GetString("LoginWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با پیامک.
        /// </summary>
        public static string LoginWithPhone {
            get {
                return ResourceManager.GetString("LoginWithPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت نیاز به تغییر رمز عبور، آن را وارد کنید.
        /// </summary>
        public static string PasswordHelper {
            get {
                return ResourceManager.GetString("PasswordHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی رمز عبور.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید تلفن همراه.
        /// </summary>
        public static string PhoneConfirm {
            get {
                return ResourceManager.GetString("PhoneConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه وارد شده برای ورود و احراز هویت استفاده می‌شود و باید منحصر به فرد باشد.
        /// </summary>
        public static string PhoneNumberHelper {
            get {
                return ResourceManager.GetString("PhoneNumberHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام با ایمیل.
        /// </summary>
        public static string RegisterWithEmail {
            get {
                return ResourceManager.GetString("RegisterWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام با موبایل.
        /// </summary>
        public static string RegisterWithPhone {
            get {
                return ResourceManager.GetString("RegisterWithPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره بمان.
        /// </summary>
        public static string RememeberMe {
            get {
                return ResourceManager.GetString("RememeberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ورود به تایید دو مرحله ای نیاز است!.
        /// </summary>
        public static string RequiresTwoFactor {
            get {
                return ResourceManager.GetString("RequiresTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس پنل.
        /// </summary>
        public static string ReturnUrl {
            get {
                return ResourceManager.GetString("ReturnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر نقشی به کاربر اختصاص داده نشود، به عنوان یک کاربر عادی در نظر گرفته خواهد شد.
        /// </summary>
        public static string RolesHelper {
            get {
                return ResourceManager.GetString("RolesHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر عزیز به {0} خوش آمدید 
        ///Code: {1}.
        /// </summary>
        public static string SmsOfLogin {
            get {
                return ResourceManager.GetString("SmsOfLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربری.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری باید منحصر به فرد باشد.
        /// </summary>
        public static string UsernameHelper {
            get {
                return ResourceManager.GetString("UsernameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی کیف پول.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت نام در سایت وجود ندارد.
        /// </summary>
        public static string WarningCanntRegister {
            get {
                return ResourceManager.GetString("WarningCanntRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما یافت نشده ، شما می توانید از طریق تلفن همراه ثبت نام نمایید..
        /// </summary>
        public static string WarningCanRegister {
            get {
                return ResourceManager.GetString("WarningCanRegister", resourceCulture);
            }
        }
    }
}
