//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamkare.Resource.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hamkare.Resource.General.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن به سبد خرید.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجود در انبار.
        /// </summary>
        public static string AvailableInStock {
            get {
                return ResourceManager.GetString("AvailableInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس بگیرید.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی مقالات.
        /// </summary>
        public static string CategoriesOfArticles_ {
            get {
                return ResourceManager.GetString("CategoriesOfArticles ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رنگ.
        /// </summary>
        public static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرات.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن نظر.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ کمیسیون.
        /// </summary>
        public static string CommissionAmount {
            get {
                return ResourceManager.GetString("CommissionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد کمیسیون.
        /// </summary>
        public static string CommissionPercentage {
            get {
                return ResourceManager.GetString("CommissionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطه تماس.
        /// </summary>
        public static string ContactPoint {
            get {
                return ResourceManager.GetString("ContactPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع واحد پولی.
        /// </summary>
        public static string CurrencyUnit {
            get {
                return ResourceManager.GetString("CurrencyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقصد.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دامنه.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات ایمیل.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظری ثبت نشده است.
        /// </summary>
        public static string EmptyComment {
            get {
                return ResourceManager.GetString("EmptyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات متداول.
        /// </summary>
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلترها.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تاسیس.
        /// </summary>
        public static string FoundingDate {
            get {
                return ResourceManager.GetString("FoundingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گارانتی.
        /// </summary>
        public static string Guarantee {
            get {
                return ResourceManager.GetString("Guarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        public static string IsColor {
            get {
                return ResourceManager.GetString("IsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جغرافیایی.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول جغرافیایی.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک نقشه.
        /// </summary>
        public static string MapLink {
            get {
                return ResourceManager.GetString("MapLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعار.
        /// </summary>
        public static string Motto {
            get {
                return ResourceManager.GetString("Motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات کار.
        /// </summary>
        public static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مالک.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام صفحه.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میسر آیکون.
        /// </summary>
        public static string PathFav {
            get {
                return ResourceManager.GetString("PathFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر لوگو.
        /// </summary>
        public static string PathLogo {
            get {
                return ResourceManager.GetString("PathLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضمانت اصالت کالا.
        /// </summary>
        public static string productAuthenticity {
            get {
                return ResourceManager.GetString("productAuthenticity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرفی کالا.
        /// </summary>
        public static string productIntroduction {
            get {
                return ResourceManager.GetString("productIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات کالا.
        /// </summary>
        public static string ProductSpecifications {
            get {
                return ResourceManager.GetString("ProductSpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecentArticles {
            get {
                return ResourceManager.GetString("RecentArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نظر.
        /// </summary>
        public static string RegisterComment {
            get {
                return ResourceManager.GetString("RegisterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثل.
        /// </summary>
        public static string SameAs {
            get {
                return ResourceManager.GetString("SameAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بخش.
        /// </summary>
        public static string SectionName {
            get {
                return ResourceManager.GetString("SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالاهای مشابه.
        /// </summary>
        public static string SimilarGoods {
            get {
                return ResourceManager.GetString("SimilarGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SourceName {
            get {
                return ResourceManager.GetString("SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام تلفنی.
        /// </summary>
        public static string TelephoneInquiry {
            get {
                return ResourceManager.GetString("TelephoneInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ پس زمینه.
        /// </summary>
        public static string ThemeBackgroundHelper {
            get {
                return ResourceManager.GetString("ThemeBackgroundHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ اصلی.
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناشناس.
        /// </summary>
        public static string UnknownPerson {
            get {
                return ResourceManager.GetString("UnknownPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل کاربری.
        /// </summary>
        public static string UserPanel {
            get {
                return ResourceManager.GetString("UserPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت نام در سایت نمی باشد!.
        /// </summary>
        public static string WarningCanRegister {
            get {
                return ResourceManager.GetString("WarningCanRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودیت در ثبت نام.
        /// </summary>
        public static string WarningTitleCanRegister {
            get {
                return ResourceManager.GetString("WarningTitleCanRegister", resourceCulture);
            }
        }
    }
}
